openapi: 3.0.1
info:
  title: monster-death-tyrant
  x-cortex-tag: monster-death-tyrant
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: aberration
    challenge_rating: 3
    legendary: true
    armor_class: 20
    hit_points: 218
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-death-tyrant
      alias: github-token-test
